// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcsBzgwuccE1X3AiNgMjrYmtU2g_3eMSY',
    appId: '1:140170902477:web:83f596474cc0d09d6a6284',
    messagingSenderId: '140170902477',
    projectId: 'social-network-37410',
    authDomain: 'social-network-37410.firebaseapp.com',
    storageBucket: 'social-network-37410.firebasestorage.app',
    measurementId: 'G-XRL9L9DPMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB54LwBOE6AphV6w2gQ8AmW7UkR8xnQVB8',
    appId: '1:140170902477:android:6ab55e31f9b0be176a6284',
    messagingSenderId: '140170902477',
    projectId: 'social-network-37410',
    storageBucket: 'social-network-37410.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAXUpTRzVIQhyJnjAUo07eeLCkoXrjmyI',
    appId: '1:140170902477:ios:a1387b165c65846f6a6284',
    messagingSenderId: '140170902477',
    projectId: 'social-network-37410',
    storageBucket: 'social-network-37410.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAXUpTRzVIQhyJnjAUo07eeLCkoXrjmyI',
    appId: '1:140170902477:ios:a1387b165c65846f6a6284',
    messagingSenderId: '140170902477',
    projectId: 'social-network-37410',
    storageBucket: 'social-network-37410.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcsBzgwuccE1X3AiNgMjrYmtU2g_3eMSY',
    appId: '1:140170902477:web:96fb5c8e1996f3d16a6284',
    messagingSenderId: '140170902477',
    projectId: 'social-network-37410',
    authDomain: 'social-network-37410.firebaseapp.com',
    storageBucket: 'social-network-37410.firebasestorage.app',
    measurementId: 'G-TJGWHD48W3',
  );
}
